version: "3"

tasks:
  init:
    cmds:
      - rm -rf .bloop/ .metals/ .bsp/
      - mill --bsp-install

  build:
    aliases: [b]
    cmds:
      - mill nativeLink
      - ln -fs "$PWD/out/nativeLink.dest/out" "$HOME/.local/bin/${PWD##*/}"

  rebuild:
    aliases: [rb]
    cmds:
      - cmd: rm -rf out/ ~/.ivy2/local/org.padhia/sfenv_*
      - task: build

  update:
    aliases: [u]
    cmds:
      - mill mill.scalalib.Dependency/showUpdates

  test:
    aliases: [t]
    cmds:
      - mill test

  clean:
    cmds:
      - rm -rf .bloop/ .bsp/ .metals/ out/ ~/.ivy2/local/org.padhia/sfenv_*
