version: "3"

tasks:
  init:
    cmds:
      - mill --bsp-install

  build:
    aliases: [b]
    cmds:
      - mill launcher
      - ln -fs "$PWD/out/launcher.dest/run" "$HOME/.local/bin/${PWD##*/}"

  assembly:
    aliases: [jar]
    cmds:
      - mill assembly
      - ln -fs "$PWD/out/assembly.dest/out.jar" "$HOME/.local/bin/${PWD##*/}"

  rebuild:
    aliases: [rb]
    cmds:
      - cmd: rm -rf out/ ~/.ivy2/local/org.padhia/sfenv_*
      - task: build

  update:
    aliases: [u]
    cmds:
      - mill mill.scalalib.Dependency/showUpdates

  test:
    aliases: [t]
    cmds:
      - mill test

  clean:
    cmds:
      - rm -rf .bloop/ .bsp/ .metals/ out/ ~/.ivy2/local/org.padhia/sfenv_*
