version: '3'

tasks:
  build:
    aliases: [b]
    cmds:
      - mill launcher
      - ln -fs "$PWD/out/launcher.dest/run" "$HOME/.local/bin/${PWD##*/}"

  assembly:
    aliases: [jar]
    cmds:
      - mill assembly
      - ln -fs "$PWD/out/assembly.dest/out.jar" "$HOME/.local/bin/${PWD##*/}"

  rebuild:
    aliases: [rb]
    cmds:
      - cmd: rm -rf out/
      - task: build

  update:
    aliases: [u]
    cmds:
      - mill mill.scalalib.Dependency/showUpdates

  test:
    aliases: [t]
    cmds:
      - mill test

  testonly:
    aliases: [to]
    cmds:
      - mill test.testOnly

  sample:
    aliases: [rr]
    cmds:
      - mill run ./sample.yaml | bat --wrap=never -l sql

  clean:
    cmds:
      - rm -rf .bloop/ .metals/ out/ ~/.ivy2/local/org.padhia/sfenv-*
