name: create a new release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: build native image (${{ matrix.os }}-${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: linux
            arch: x86_64
            runner: ubuntu-latest
            ext: ""
          - os: linux
            arch: aarch64
            runner: ubuntu-24.04-arm
            ext: ""
          - os: macos
            arch: aarch64
            runner: macos-latest
            ext: ""
          - os: windows
            arch: x86_64
            runner: windows-latest
            ext: ".exe"
    steps:
      - uses: actions/checkout@v5

      - name: install mill (unix)
        if: matrix.os != 'windows'
        run: |
          curl -L https://repo1.maven.org/maven2/com/lihaoyi/mill-dist/1.1.2/mill-dist-1.1.2-mill.sh -o mill
          chmod +x mill

      - name: install mill (windows)
        if: matrix.os == 'windows'
        run: |
          curl -L https://repo1.maven.org/maven2/com/lihaoyi/mill-dist/1.1.2/mill-dist-1.1.2-mill.bat -o mill.bat

      - name: build native image (unix)
        if: matrix.os != 'windows'
        run: ./mill nativeImage

      - name: build native image (windows)
        if: matrix.os == 'windows'
        run: .\mill.bat nativeImage

      - name: rename binary
        shell: bash
        run: mv "out/nativeImage.dest/native-executable" "out/nativeImage.dest/sfenv-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}"

      - name: upload release asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: out/nativeImage.dest/sfenv-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
