name: create a new release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: build a binary distribution
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - uses: jodersky/setup-mill@master
      with:
        mill-version: 0.11.6

    - name: build assembly
      run: mill assembly

    - name: rename assembly
      run: mv out/assembly.dest/out.jar out/assembly.dest/sfenv

    - name: Upload assembly
      id: upload-release-asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./out/assembly.dest/sfenv
